function getRandomGreeting() {
  var greetings = [
    "Beep boop! Are you a robot?",
    "How many sides does a circle have?",
    "You can read btw",
    "Made you look!",
    "Redbull gives you wings...",
    "As seen on TV!",
    "doot doot",
    "Cold as ice!",
    "Made in the US!",
    "Reload the page NOW!",
    "Running vertex.exe",
    "WARNING: You may lose braincells if you proceed!",
    "Do you bite your ice cream?",
    "#Relatable",
    "You got games on your phone?",
    "Powered by hamsters!",
    "*insert cool explosion*",
    "Got to go fast!",
    "Powered by 128 Gigs of RAM!",
    "Powered by 16MB of RAM!",
    "w h a t",
    "what the dog doin?",
    "I'm gonna pop some tags",
    "thx stackoverflow!",
    "are you a gaemer?",
    "It is time to get funky!",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Microsoft Edge, you need some help.",
    "Living in Spain without the S",
    "youtube.com/watch?v=dQw4w9WgXcQ",
    "bottem text",
    "No fun allowed",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for another message",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "Trust me, I did not copy Minecraft with this",
    "It is everyday bro",
    "What's my age again?",
    "This is the 5th time this week, and it's only Monday",
    "You bum",
    "Toss the Turtle is pretty fun",
    "Mission failed, we will get them next time",
    "NUKE INCOMING!",
    "Sharp games, smooth edges.",
    "Every great game has a vertex.",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
